#!/usr/bin/env python
# -*- coding: utf-8 -*-

def helloworld():
    ''' simple greeting '''
    return "babsutils 1.0 says hello world!"

def sumup(a,b):
    ''' return the sum of the parameters '''
    return a + b
